pipeline {
    agent any

    parameters {
        string(name: 'TEST_ID', defaultValue: '', description: 'Enter specific test ID to run (e.g. LOG-TC-001). Leave blank to run all tests.')
    }

    environment {
        // Set environment variables if needed
        CI = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout source code from SCM
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                // Using bat since the environment is Windows
                bat 'npm install'
                bat 'npx playwright install --with-deps' // Install all Playwright browsers
            }
        }

        stage('Build') {
            steps {
                bat 'npm run build'
            }
        }

        stage('Run Tests') {
            steps {
                // catchError ensures the pipeline continues to the post block even if tests fail
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    script {
                        if (params.TEST_ID?.trim()) {
                            echo "Running specific test ID: ${params.TEST_ID}"
                            bat "npx playwright test -g \"${params.TEST_ID}\" --reporter=line,allure-playwright"
                        } else {
                            echo "Running default test suite"
                            bat 'npm run test:allure'
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            // Always generate the Allure HTML report from raw results before archiving
            script {
                try {
                    bat 'npx allure generate allure-results --clean -o allure-report'
                } catch (Exception e) {
                    echo "Could not generate allure HTML report (maybe no results were found)"
                }
            }

            // Archive Allure HTML Report generated by npm run allure:generate
            archiveArtifacts artifacts: 'allure-report/**/*', allowEmptyArchive: true

            // Archive Playwright HTML report
            archiveArtifacts artifacts: 'playwright-report/**/*', allowEmptyArchive: true
            
            // Archive JUnit TestNG results
            archiveArtifacts artifacts: 'test-results/testng-results.xml', allowEmptyArchive: true

            // If you have the Jenkins Allure Plugin installed, you can uncomment the following lines
            // script {
            //     try {
            //         allure([
            //             includeProperties: false,
            //             jdk: '',
            //             properties: [],
            //             reportBuildPolicy: 'ALWAYS',
            //             results: [[path: 'allure-results']]
            //         ])
            //     } catch (Exception e) {
            //         echo "Jenkins Allure plugin not installed or configured. Falling back to archived allure-report."
            //     }
            // }
        }
        cleanup {
            // Clean workspace to save space
            cleanWs()
        }
    }
}
