pipeline {
    agent any

    environment {
        // Set environment variables if needed
        CI = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout source code from SCM
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                // Using bat since the environment is Windows
                bat 'npm install'
                bat 'npx playwright install --with-deps' // Install all Playwright browsers
            }
        }

        stage('Build') {
            steps {
                bat 'npm run build'
            }
        }

        stage('Run Tests') {
            steps {
                // catchError ensures the pipeline continues to the post block even if tests fail
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    // Running default test suite with Allure
                    // If you want to parameterize this, you can replace this with bat "npm run ${params.TEST_SUITE}"
                    bat 'npm run test:allure'
                }
            }
        }
    }

    post {
        always {
            // Archive Allure HTML Report generated by npm run allure:generate
            archiveArtifacts artifacts: 'allure-report/**/*', allowEmptyArchive: true

            // Archive Playwright HTML report
            archiveArtifacts artifacts: 'playwright-report/**/*', allowEmptyArchive: true
            
            // Archive JUnit TestNG results
            archiveArtifacts artifacts: 'test-results/testng-results.xml', allowEmptyArchive: true

            // If you have the Jenkins Allure Plugin installed, you can uncomment the following lines
            // script {
            //     try {
            //         allure([
            //             includeProperties: false,
            //             jdk: '',
            //             properties: [],
            //             reportBuildPolicy: 'ALWAYS',
            //             results: [[path: 'allure-results']]
            //         ])
            //     } catch (Exception e) {
            //         echo "Jenkins Allure plugin not installed or configured. Falling back to archived allure-report."
            //     }
            // }
        }
        cleanup {
            // Clean workspace to save space
            cleanWs()
        }
    }
}
